-- migrate:up
CREATE TABLE accounts (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    uid VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    encrypted_password VARCHAR(200) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);



-- migrate:down
DROP TABLE accounts;
